In [26]:
import numpy as np 
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(A)
B = np.flip(A, axis=0)
print(B)
C = np.flip(B, axis=1)
print(C)
for i in range(-1, 2):
    print(i)

B = np.array([[1, 2], [3, 4]])
print(B[0:-1, 0:-1])
print(np.mean(B))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[7 8 9]
 [4 5 6]
 [1 2 3]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]
-1
0
1
[[1]]
2.5


In [27]:
print(1621/(7*8*9))

3.2162698412698414


In [34]:
print(B.argmax)
print(B.shape)
y,x = (np.unravel_index(B.argmax(), B.shape))
print(y, x)

<built-in method argmax of numpy.ndarray object at 0x000000000757F940>
(2, 2)
(2, 2)
1 1


In [36]:
a = 1
assert a == 1, "Even dimensions for filters is not allowed!"

In [37]:
x = np.array([[1, 2], [3, 4]])
v = np.array([9, 10])
print(np.outer(x, v))

[[ 9 10]
 [18 20]
 [27 30]
 [36 40]]


In [47]:
k1 = np.array([[1], [4], [6], [4], [1]])
k2 = np.array([[1, 4, 6, 4, 1]])
print(np.dot(k1, k2))

[[ 1  4  6  4  1]
 [ 4 16 24 16  4]
 [ 6 24 36 24  6]
 [ 4 16 24 16  4]
 [ 1  4  6  4  1]]


In [55]:
x1 = np.array([[1, 2], [3, 4]])
x2 = np.array([[1, 2]])
print(x1,'\n', x2)
print(' ')
print(np.dot(x1, x2))

print(np.outer(x1, x2))

print(' \n', x1 * x2)

[[1 2]
 [3 4]] 
 [[1 2]]
 


ValueError: shapes (2,2) and (1,2) not aligned: 2 (dim 1) != 1 (dim 0)